
# Vitenskapsfilosofi

## Introduksjon

Jeg har valgt å besvare oppgave 2 og 3 i dette arbeidskravet og deler arbeidskravet inn i 2 deler.

Del 1 "Gi en kort beskrivelse og forklaring av falsifikasjonisme. Presenter så ett problem med denne teorien. Tror du problemet kan løses? Begrunn svaret ditt."

Del 2 "Oppgave 2: Forklar de grunnleggende ideene i Bayesianisme. Hva er noen av fordelene med Bayesianisme sammenlignet med alternativene? (for eksempel, HD-teorien eller abduktivisme). Presenter ett problem med Bayesianisme og evaluer hvor alvorlig problemet er."

## Del 1

### Beskrivelse og forklaring av falsifikasjonisme

Falsifikasjon er en teori innen vitenskapsfilosofi som kjennetegnes ved at teorier (hypoteser) er falsifiserbare (motvisbare). Det motsatte er at teorier er verifiserbare (bekreftet).

Gjennom store deler av det 20.århundre var problemet med bekreftelse av teorier en stor utfordring for filosofene.

Gruppen teoretiske empirister bygde opp "induktiv logikk" for å hjelpe oss med å forstå testing i vitenskap. De lagde seg enkle hypoteser, men dette feilet (f.eks. at alle ravner er svarte). (Bayesianism and modern theories of evidence).

Karl Popper likte denne situasjonen da han mente at induktiv logikk var en fiasko fordi induksjonsproblemet er vanskelig/umulig å løse.
Derfor sa Popper at "S er en vitenskapelig påstand hvis og bare hvis S er falsifiserbar" (Popper,1959).

Poppers defisjon på falsibarhet er "S er falsifiserbar hvis og bare hvis man kan deduktivt utlede en prediksjon fra S som kan empirisk sjekkes".

Popper kom med ideen om at vitenskapen måtte "gi slipp på at en teori kan bekreftes" fordi ingen vitenskapelige teorier kan bekreftes.
Popper mente videre at induksjonen var vanskelig på grunn av utfordringen med på å skille vitenskapelige hypoteser fra ikke-vitenskapelige hypoteser og at vitenskap kun må bruke falsifisering.
Han mente at det bare kunne være falsifiserbare hypoteser for at det skal være ekte vitenskap. Desto mer man kunne gradere falsifiseringen med flere eller mer presise prediksjoner (antagelser), desto bedre vitenskap.


Poppers favoritt teori er Einstein relativitets teori. Den er svært falsifiserbar, og den har overlevd nye prediksjoner og falsifiseringer. Den er det som kalles korroborert (overlevd mange tester), og den er sannsynligvis sann (men ikke bekreftet).

Popper vitenskapelige syklusen; komme opp med nye prediksjoner og falsifiseringer, "så tvil hele veien", "man kan aldri bli sikker"


### Problemet med falsifikasjonisme, Poppers og Duhems læsning på problemet

Innen falsifikasjonisme er en hypotese vitenskapelig hvis, og bare hvis, den er falsifiserbar. 
Pierre Duhem, en fransk filosof, kom med noen logiske poeng, og utfordret Popper.

Et eksperiment som støter på et problem, vil ikke kunne gi svar på hvor feilen ligger uten støttehypoteser og bekreftelser. Popper ønsket ikke bekreftelser i vitenskap, så her fikk falsifikasjonen et problem. Duhem mente at falsifisering krever (vanligvis) bekreftelse, og bekreftelse krever induksjon!

Avslutter del 1 med Duhems ord: "Det eneste eksperimentet lærer oss er at blant forslagene som brukes til å forutsi fenomenet og for å fastslå om det ville bli produsert, er det minst en feil; men hvor denne feilen ligger, er akkurat det eksperimentet ikke forteller oss."

## Del 2

## Bayesianisme og Bayes Theorem

Bayesianisme bruker kvantitativ sannsynlighetsregning og induktiv logikk. Det vil si at man ønsker å forstå bevis ved hjelp av sannsynlighetsteori, som å regne ut sannsynligheten for at noe inntreffer gitt en annen hendelse.

Om det er en usikkerhet omkring en hypotese, vil observasjonsbevis noen ganger heve eller senke sannsynligheten for hypotesen.

Vi snakker ofte om muligheter som mer eller mindre sannsynlige. Forskere snakker også om hypoteser som sannsynlige eller usannsynlige gitt vitenskapelig kunnskap og eksperimentelle funn. Dette er ofte kjent som P(X) er sannsynligheten for at p??standen X er sann. Et enkelt eksempel er: P(det regner senere) er sannsynligheten for at det regner senere.

Thomas Bayes, en engelsk statistikker og matematiker, prøvde seg på et utsagn som viste seg å stemme for å regne ut sannsynlighet for en påstand hvor nye bevis kommer frem og stiller spørsmålstegn ved hypotesen. Dette ble kalt Bayes Theorem. Med Bayes Theorem ønsker vi en rasjonell oppdatering av sannsynligheter ettersom bevis kommer inn.

Formelen for Bayes' teorem er: P(h\|e) = \[P(e\|h) \* P(h)\] / P(e)

Vi leser "h" som hypotese og "e" som bevis. Videre forståelse er:

P(h\|e) representerer sannsynligheten for at hendelse h skal skje gitt at hendelse "e" har skjedd.

P(e\|h) er sannsynligheten for at hendelse e skal skje gitt at hendelse h har skjedd. Sannsynlighet for formen P(e\|h) blir ofte kalt "likelihoods" ("sannsynligheter").

P(h) er den tidligere sannsynligheten for at hendelse "h" skal skje uten å vurdere bevis.

P(e) er den tidligere sannsynligheten for at hendelse "e" skal skje uten å vurdere bevis.

Bayes teorem forteller oss altså om relasjonen mellom P(h) og P(h\|e) og at ved nye bevis "e" vil "dagens sannsynlighet bli morgendagens tidligere sannsynlighet". En oppdatert versjon kan derfor være: P~ny~(h) = P~gammel~(h\|e).

## HD metoden

Står for den Hypotetisk deduktive metoden. Den er ikke matematisk og bruker kvalitativ metode. En god HD teori blir bekreftet flere ganger.

Trinnene i teorien er fra Hempel på 1950 tallet:

Trinn 1: Formuler en teori eller hypotese -- en "utdannet gjetning".\
Trinn 2: Utled empiriske konsekvenser fra teorien/hypotesen med deduksjon.\
Trinn 3: Test disse empiriske konsekvensene mot observasjoner eller eksperiment.\
Trinn 4: Hvis de empiriske konsekvensene viser seg å være riktige, er teorien (induktivt)\
bekreftet til en viss grad.

Et problem med HD teorien er at den har kun 2 kategorier (falsifisert og bekreftet), og at den ikke skiller mellom enkle og kompliserte hypoteser så lenge de kan bekreftes.

F.eks. dersom 2 teorier som testes kan begge bekreftes (selv om vi egentlig bare ønsker at en av de skal bekreftes). Et prinsipp man bør følge "enkle teorier/hypoteser foretrekkes fremfor vanskeligere teorier" (Ockhams barberkniv). I HD teorien velger man alle data/teori som er bekreftet og skiller ikke på at noen er bedre enn andre.

## Adbuktivisme

Denne er også ikke matematisk og den bruker kvalitativ forklaring. Metoden er deduktiv og er også kjent som "slutning til den beste forklaringen" eller at "Ingen annen tilgjengelig teori ville gi samme/like god forklaring". En teori bør gi en forklaring på mange/flere typer datasett, kalt forklaringskraft. Vi velger enkle forklaringer fremfor kompliserte, kalt enkelhet. F.eks. Relativitets teorien er en veldig enkel teori (enkelhet), men har presise forklaringer (forklaringskraft).

### HD-teori og Abduktivisme vs Bayesinisme

Vitenskapelige teorier har til hensikt å fortelle oss hva vi gjerne vil se. Forskjellen på HD-metoden og Abduktivisme, sammenlignet med Bayesinisme er at de to første bruker deduktiv logikk (de får bekreftelse) og kvalitative metoder. Bayesinisme bruker sannsynlighetsregning, induktiv logikk og en kvantitative metode.

### Utfordringen med Bayesianisme og evaluering av hvor alvorlig problemet er

En utfordring med bayesinisme er at hypotesene alltid må tallfestes. Utfordringen kommer gjerne som hva er det egentlig P(h) måler? Hvordan kan vi tolke gammel mot ny P(h)?

Så om vi ønsker å bruke Bayes theorem, så trenger vi en tolkning av sannsynlighet som vil tillate oss å snakke om tidligere sannsynlighet. Det er dette bayesianerne har utviklet og det kaller det for subjektivistisk tolkning.

Ideen bak  subjektiv bayesinisme er at tro og sannsynlighetsregning er basert på en persons tro på et gitt tidspunkt. Det kommer gjerne inn nye bevis eller obervasjoner som setter spørsmålstegn på om påstanden er sann eller usann.

Et problem med bayesinisme kan derfor være at sannsynlighetsregningen er subjektiv og at mangel på enighet kan være utfordrende da nye bevis kommer. En annen utfordring kan være at det er vanskeligere å velge mellom to teorier når sannsynligheten er basert på en subjektiv måte.




## Referanser
