project:
  type: book

book:
  title: "Eksamen IDR4000"
  author: "410"
  date: "2023-11-15"
  chapters:
    - index.qmd
    - part1.qmd
    - part2.qmd
    - part3.qmd
    - part4.qmd
    - part5.qmd
    - part6.qmd
    - part7.qmd
    - references.qmd

bibliography: referanser.bib

crossref: 
  fig-labels: arabic
  fig-title: "Figur"
  tbl-labels: arabic
  tbl-title: "Tabell"

format:
  pdf:
    documentclass: scrreprt
    number-sections: false



